title: Codengine
author: Kenose Osedeme
email: kenosedeme@gmail.com
description: > My special corner
# social links
twitter_username: https://twitter.com/thekenose # DO NOT include the @ character, or else the build will fail!
github_username:  Kenolise # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
